//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type RCIn struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Rssi        uint8
	Channels    []uint16
}
