//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/geometry_msgs"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type Vibration struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Vibration   geometry_msgs.Vector3
	Clipping    [3]float32
}
