//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type LogData struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Id          uint16
	Offset      uint32
	Data        []uint8
}
