//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
)

type Char struct {
	msg.Package `ros:"std_msgs"`
	Data        uint8 `rostype:"char"`
}
