//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"time"

	"github.com/techloopdev/goroslib/v2/pkg/msg"
)

type Duration struct {
	msg.Package `ros:"std_msgs"`
	Data        time.Duration
}
