//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type GeoPointStamped struct {
	msg.Package `ros:"geographic_msgs"`
	Header      std_msgs.Header
	Position    GeoPoint
}
