//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/geometry_msgs"
)

type GeoPose struct {
	msg.Package `ros:"geographic_msgs"`
	Position    GeoPoint
	Orientation geometry_msgs.Quaternion
}
