//autogenerated:yes
//nolint:revive,lll
package vision_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/sensor_msgs"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type Detection3D struct {
	msg.Package `ros:"vision_msgs"`
	Header      std_msgs.Header
	Results     []ObjectHypothesisWithPose
	Bbox        BoundingBox3D
	SourceCloud sensor_msgs.PointCloud2
}
