//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
)

type Point32 struct {
	msg.Package `ros:"geometry_msgs"`
	X           float32
	Y           float32
	Z           float32
}
