//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type PolygonStamped struct {
	msg.Package `ros:"geometry_msgs"`
	Header      std_msgs.Header
	Polygon     Polygon
}
