//autogenerated:yes
//nolint:revive,lll
package velodyne_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type VelodyneScan struct {
	msg.Package `ros:"velodyne_msgs"`
	Header      std_msgs.Header
	Packets     []VelodynePacket
}
