//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
)

type QueryCalibrationStateReq struct {
	msg.Package `ros:"control_msgs"`
}

type QueryCalibrationStateRes struct {
	msg.Package  `ros:"control_msgs"`
	IsCalibrated bool
}

type QueryCalibrationState struct {
	msg.Package `ros:"control_msgs"`
	QueryCalibrationStateReq
	QueryCalibrationStateRes
}
