//autogenerated:yes
//nolint:revive,lll
package sensor_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/geometry_msgs"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type MultiDOFJointState struct {
	msg.Package `ros:"sensor_msgs"`
	Header      std_msgs.Header
	JointNames  []string
	Transforms  []geometry_msgs.Transform
	Twist       []geometry_msgs.Twist
	Wrench      []geometry_msgs.Wrench
}
