//autogenerated:yes
//nolint:revive,lll
package sensor_msgs

import (
	"github.com/techloopdev/goroslib/v2/pkg/msg"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/geometry_msgs"
	"github.com/techloopdev/goroslib/v2/pkg/msgs/std_msgs"
)

type MagneticField struct {
	msg.Package             `ros:"sensor_msgs"`
	Header                  std_msgs.Header
	MagneticField           geometry_msgs.Vector3
	MagneticFieldCovariance [9]float64
}
